development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: <%= ENV['RAILS_DB_NAME'] %>
  pool: 5
  username: <%= ENV['RAILS_DB_USER'] %>
  password: <%= ENV['RAILS_DB_PASSWORD'] %>

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: <%= ENV['RAILS_DB_NAME'] %>
  pool: 5
  username: rails
  password: <%= ENV['RAILS_DB_PASSWORD'] %>

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: <%= ENV['RAILS_DB_NAME'] %>
  pool: 5
  username: rails
  password: <%= ENV['RAILS_DB_PASSWORD'] %>
